[project]
name = "passport-timer-bot"
version = "0.1.0"
description = ""
authors = ["Vlad <your@email.com>"]
requires-python = ">=3.11"

dependencies = [
  "flask",
  "apscheduler",
  "python-telegram-bot",
  "pytz"
]
